
name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd Zad1
          pip install nose2 parameterized pyhamcrest wheel coverage
          cd ../Zad2
          pip install nose2 parameterized coverage
          cd ../Zad3
          pip install nose2 coverage
          cd ..
      - name: Run tests for exercises 1,2,3
        run: |
            python -m nose2 --with-coverage Zad2
            python -m nose2 --with-coverage Zad3
            cd Zad1
            python -m coverage run setup.py test
      - name: Coveralls Python
        uses: AndreMiras/coveralls-python-action@v20201129

            