
name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nose2
      - name: Run tests for exercises 1,2,3
        run: |
            nose2
            nose2 --with-coverage
            