
name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nose2 parametrized pyhamcrest wheel coverage
      - name: Run tests for exercises 1,2,3
        run: |
            python -m nose2 --with-coverage Zad2
            python -m nose2 --with-coverage Zad3
            cd Zad1
            python -m coverage run setup.py test
            